"""add education_progress table

Revision ID: 062ec468924f
Revises: a1b2c3d4e5f6
Create Date: 2026-08-21 20:48:24.442967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '062ec468924f'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('completed_lesson_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_progress_user_id'), 'education_progress', ['user_id'], unique=True)
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed NOT NULL tightening on unrelated
    # pre-existing columns (budgets/forecasts/goals/recommendations/
    # transactions.user_id) — dropped from this migration since it's
    # pre-existing drift unrelated to this change, not something to fold in
    # silently here.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_education_progress_user_id'), table_name='education_progress')
    op.drop_table('education_progress')
    # ### end Alembic commands ###
